sudo: false

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

os:
- osx
- linux

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  # linting
  - npm run ci-lint
  # compatibility testing
  - npm run cover
  - npm run check

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
