language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "stable"

os:
- osx
- linux
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode8
    - os: linux
      sudo: false

install:
  - travis_retry npm install

script:
  - node --version
  - npm --version
  # linting
  - npm run lint
  # compatibility testing
  - npm run cover
  - npm run check

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
